---
kind: pipeline
type: docker
name: skuid-cli

workspace:
  base: /go
  path: src/github.com/skuid/tides

volumes:
  - name: output
    temp: {}

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: test
    image: golang:1.18-alpine
    commands:
      - apk add git
      - make ci # fails if coverage is below 85%; see MainTest for details
    environment:
      CGO_ENABLED: '0'
  - name: build
    image: golang:1.18-alpine
    commands:
      - make release
    environment:
      CGO_ENABLED: '0'
    volumes:
      - name: output
        path: /tmp/dist
    when:
      event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_key
      files: /tmp/dist/*
    volumes:
      - name: output
        path: /tmp/dist
    when:
      event: tag
