---
kind: pipeline
type: docker
name: skuid-cli

workspace:
  base: /go
  path: src/github.com/skuid/skuid-cli/

volumes:
  - name: output
    temp: {}

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: test
    image: golang:1.23.1-alpine
    commands:
      - apk add git
      - go test -v -cover -short ./...
    environment:
      CGO_ENABLED: '0'
