---
kind: pipeline
type: docker
name: skuid-cli

workspace:
  base: /go
  path: src/github.com/skuid/skuid-cli

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: test
    image: golang:1.15-alpine
    commands:
      - apk add git
      - go test -v ./...
    environment:
      CGO_ENABLED: '0'

  - name: build
    dockerfile: compose/Dockerfile
    environment:
      CGO_ENABLED: '0'
    volumes:
      - name: output
        path: /tmp/dist
    when:
      event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_key
      files: /tmp/dist/*
    volumes:
      - name: output
        path: /tmp/dist
    when:
      event: tag

volumes:
  - name: output
    temp: {}