workspace:
  base: /go
  path: src/github.com/skuid/skuid-cli

pipeline:
  fetch:
    image: alpine/git
    commands:
      - git fetch --tags
  test:
    image: golang:1.15-alpine
    commands:
      - apk add git
      - go test -v ./...
    environment:
      CGO_ENABLED: '0'

  build:
    dockerfile: compose/Dockerfile
    environment:
      CGO_ENABLED: '0'
    volumes:
      - output:/tmp/dist
    when:
      event: tag
  release:
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_key
      files: /tmp/dist/*
    volumes:
      - output:/tmp/dist
    when:
      event: tag

volumes:
  output:
    temp: {}
