// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ZipFile is an autogenerated mock type for the ZipFile type
type ZipFile struct {
	mock.Mock
}

type ZipFile_Expecter struct {
	mock *mock.Mock
}

func (_m *ZipFile) EXPECT() *ZipFile_Expecter {
	return &ZipFile_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: p
func (_m *ZipFile) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ZipFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type ZipFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *ZipFile_Expecter) Write(p interface{}) *ZipFile_Write_Call {
	return &ZipFile_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *ZipFile_Write_Call) Run(run func(p []byte)) *ZipFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ZipFile_Write_Call) Return(n int, err error) *ZipFile_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ZipFile_Write_Call) RunAndReturn(run func([]byte) (int, error)) *ZipFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewZipFile creates a new instance of ZipFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewZipFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *ZipFile {
	mock := &ZipFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
