// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	metadata "github.com/skuid/skuid-cli/pkg/metadata"
	mock "github.com/stretchr/testify/mock"
)

// ArchiveFilter is an autogenerated mock type for the ArchiveFilter type
type ArchiveFilter struct {
	mock.Mock
}

type ArchiveFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *ArchiveFilter) EXPECT() *ArchiveFilter_Expecter {
	return &ArchiveFilter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *ArchiveFilter) Execute(_a0 metadata.MetadataEntityFile) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(metadata.MetadataEntityFile) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ArchiveFilter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ArchiveFilter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 metadata.MetadataEntityFile
func (_e *ArchiveFilter_Expecter) Execute(_a0 interface{}) *ArchiveFilter_Execute_Call {
	return &ArchiveFilter_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *ArchiveFilter_Execute_Call) Run(run func(_a0 metadata.MetadataEntityFile)) *ArchiveFilter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MetadataEntityFile))
	})
	return _c
}

func (_c *ArchiveFilter_Execute_Call) Return(_a0 bool) *ArchiveFilter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArchiveFilter_Execute_Call) RunAndReturn(run func(metadata.MetadataEntityFile) bool) *ArchiveFilter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewArchiveFilter creates a new instance of ArchiveFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArchiveFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArchiveFilter {
	mock := &ArchiveFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
