package constants

// SKUID ENVIRONMENT VARIABLE NAMES
const (
	ENV_SKUID_HOST     = "SKUID_HOST"
	ENV_SKUID_PASSWORD = "SKUID_PW"
	ENV_SKUID_USERNAME = "SKUID_UN"
)

// pliny
const (
	ENV_PLINY_HOST = "PLINY_HOST"
)

const (
	ENV_SKUID_VERBOSE          = "SKUID_VERBOSE"
	ENV_SKUID_DEFAULT_FOLDER   = "SKUID_DEFAULT_FOLDER"
	ENV_SKUID_LOGGING_LOCATION = "SKUID_LOGGING_DIRECTORY"
	ENV_SKUID_FILE_LOGGING     = "SKUID_FILE_LOGGING"
	ENV_SKUID_FIELD_LOGGING    = "SKUID_FIELD_LOGGING"
	ENV_SKUID_IGNORE_SKUIDDB   = "SKUID_IGNORE_SKUIDDB"
	ENV_SKUID_RETRIEVE_SINCE   = "SKUID_RETRIEVE_SINCE_DATE"
	ENV_SKUID_TRACE            = "SKUID_TRACE"
	ENV_SKUID_APP_NAME         = "SKUID_APP_NAME"
	// TODO: This can be removed once https://github.com/skuid/skuid-cli/issues/150 is resolved
	ENV_SKUID_SKIP_DATASOURCES = "SKUID_SKIP_DATASOURCES"
)

const (
	TEST_ENVIRONMENT_FILE = ".testenv"
)
