package constants

// SKUID ENVIRONMENT VARIABLE NAMES
const (
	ENV_SKUID_HOST          = "SKUID_HOST"
	ENV_SKUID_PASSWORD      = "SKUID_PW"
	ENV_SKUID_USERNAME      = "SKUID_UN"
	ENV_SKUID_CLIENT_ID     = "SKUID_CLIENT_ID"
	ENV_SKUID_CLIENT_SECRET = "SKUID_CLIENT_SECRET"
)

// SERVICE PROXY ENVIRONMENT VARIABLE NAMES
const (
	ENV_METADATA_SERVICE_PROXY = "METADATA_SERVICE_PROXY"
	ENV_DATA_SERVICE_PROXY     = "DATA_SERVICE_PROXY"
)

const (
	ENV_VERBOSE = "TIDES_VERBOSE"
)

const (
	TEST_ENVIRONMENT_FILE = ".testenv"
	ENVIRONMENT_FILE      = ".env"
)
