name: Veracode Upload and Scan on Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  veracode_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy and vendor Go dependencies
      run: |
        go mod tidy
        go mod vendor
    - name: Package Go source code for Veracode
      run: |
        mkdir -p veracode_artifact/src
        rsync -av ./ veracode_artifact/src/ \
          --exclude '.git*' \
          --exclude '.github*' \
          --exclude 'compose/*' \
          --exclude '*_test.go' \
          --exclude 'README.md' \
          --exclude 'LICENSE' \
          --exclude 'Makefile' \
          --exclude '*.sh' \
          --exclude '*.yml' \
          --exclude 'veracode_artifact/*'
        cd veracode_artifact
        zip -r app.zip src

    - name: Upload and Scan with Veracode
      uses: veracode/veracode-uploadandscan-action@0.2.8
      with:
        appname: 'Nintex Apps Skuid - skuid-cli'
        createprofile: true
        filepath: 'veracode_artifact/app.zip'
        version: ${{ github.event.release.tag_name || github.run_number }}
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}
